version: "3"
services:
  cc_pulse:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: cc_pulse
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    env_file:
      - ../.env
    restart: always
